#ifndef __S2_SUBPAGE_SET_INTERFACE_V_0_1_H__
#define __S2_SUBPAGE_SET_INTERFACE_V_0_1_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_SUBPAGE_SET_INTERFACE_V_0_1_SUBPAGE_SET_DIG_INPUT 0


/*
* ANALOG_INPUT
*/



#define __S2_SUBPAGE_SET_INTERFACE_V_0_1_SUBPAGE_SET_PAGE_POSITION_SUBPAGE_INDEX_ANALOG_INPUT 0
#define __S2_SUBPAGE_SET_INTERFACE_V_0_1_SUBPAGE_SET_PAGE_POSITION_SUBPAGE_INDEX_ARRAY_LENGTH 8
#define __S2_SUBPAGE_SET_INTERFACE_V_0_1_PAGE_POSITION_SUBPAGE_INDEX_IN_ANALOG_INPUT 8
#define __S2_SUBPAGE_SET_INTERFACE_V_0_1_PAGE_POSITION_SUBPAGE_INDEX_IN_ARRAY_LENGTH 8

/*
* DIGITAL_OUTPUT
*/
#define __S2_SUBPAGE_SET_INTERFACE_V_0_1_SUBPAGE_SET_FB_DIG_OUTPUT 0


/*
* ANALOG_OUTPUT
*/


#define __S2_SUBPAGE_SET_INTERFACE_V_0_1_PAGE_POSITION_SUBPAGE_INDEX_OUT_ANALOG_OUTPUT 0
#define __S2_SUBPAGE_SET_INTERFACE_V_0_1_PAGE_POSITION_SUBPAGE_INDEX_OUT_ARRAY_LENGTH 8

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_SUBPAGE_SET_INTERFACE_V_0_1 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __SUBPAGE_SET_PAGE_POSITION_SUBPAGE_INDEX );
   DECLARE_IO_ARRAY( __PAGE_POSITION_SUBPAGE_INDEX_IN );
   DECLARE_IO_ARRAY( __PAGE_POSITION_SUBPAGE_INDEX_OUT );
};

START_NVRAM_VAR_STRUCT( S2_SUBPAGE_SET_INTERFACE_V_0_1 )
{
};



#endif //__S2_SUBPAGE_SET_INTERFACE_V_0_1_H__

